### ISSUE TITLE
API Development Tracking

### ISSUE THREAD

**Issue by PietrH** [inbo/etn#281]
This issue is a tracker of what functions have been rewritten to use the API.

## Functions implemented in etnservice

- [x] connect_to_etn
- [x] download_acoustic_dataset
- [x] get_deployments
- [x] get_detections
- [x] get_projects
- [x] get_receivers
- [x] list_network_project_codes
- [x] list_tag_ids
- [x] get_acoustic_deployments
- [x] get_acoustic_detections
- [x] get_acoustic_projects
- [x] get_acoustic_receivers
- [x] get_animal_projects
- [x] get_animals
- [x] get_cpod_projects
- [x] get_tags
- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [x] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [x] list_values
- [x] write_dwc

## Functions rewritten to use the API

- [ ] connect_to_etn
- [x] download_acoustic_dataset
- [x] get_deployments
- [x] get_detections
- [x] get_projects
- [x] get_receivers
- [x] list_network_project_codes
- [x] list_tag_ids
- [x] get_acoustic_deployments
- [x] get_acoustic_detections
- [x] get_acoustic_projects
- [x] get_acoustic_receivers
- [x] get_animal_projects
- [x] get_animals
- [x] get_cpod_projects
- [x] get_tags
- [x] list_acoustic_project_codes
- [x] list_acoustic_tag_ids
- [x] list_animal_ids
- [x] list_animal_project_codes
- [x] list_cpod_project_codes
- [x] list_deployment_ids
- [x] list_receiver_ids
- [x] list_scientific_names
- [x] list_station_names
- [x] list_tag_serial_numbers
- [x] write_dwc

**Comment by PietrH** [comment]
Refer to #280 for the logistics around how we plan to handle backwards compatibility.

**Comment by PietrH** [comment]
There is possibly a permissions issue regarding `write_dwc()`, the function has been adapted on the side of `etnservice` to return a list object, to be further processed on the client side. 

However at the moment I'm getting a HTTP 403 Forbidden error. I've contacted VLIZ about this.

**Comment by PietrH** [comment]
`write_dwc` is currently not working on the etnservice side, with a permission http error. I've deleted the test from postman to avoid monitor failure.

**Comment by PietrH** [comment]
vcr for tests, memoise for caching internally in the functions? (for list functions especially)
